version: '3.4'

services:
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    # If running on Linux, uncomment the next two lines:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
